function banknotes = banknote_definitions()
% BANKNOTE_DEFINITIONS - הגדרות שטרות (ILS, EUR)
% צבעים ב-HSV: [Hue (0-360), Saturation (0-100), 0]

    % קנה מידה: אותו PX_PER_MM כמו מטבעות - כיול חדש
    PX_PER_MM = 6.40;  % ✅ כיול מהתמונה
    
    banknotes = struct('Name', {}, 'Value', {}, 'Currency', {}, ...
                       'WidthMM', {}, 'HeightMM', {}, 'WidthPx', {}, 'HeightPx', {}, ...
                       'AspectRatio', {}, 'DominantColor', {});
    
    % --- שקל חדש (ILS) ---
    % מידות: כל השטרות 138mm × 71mm
    % צבעים ב-Hue: אדום=0/360, כתום=30, צהוב=60, ירוק=120, כחול=210, סגול=270
    
    banknotes(end+1) = struct('Name', '20 NIS', 'Value', 20, 'Currency', 'ILS', ...
        'WidthMM', 138, 'HeightMM', 71, ...
        'WidthPx', round(138*PX_PER_MM), 'HeightPx', round(71*PX_PER_MM), ...
        'AspectRatio', 138/71, 'DominantColor', [90, 50, 0]); % ירוק בהיר - Hue=90
    
    banknotes(end+1) = struct('Name', '50 NIS', 'Value', 50, 'Currency', 'ILS', ...
        'WidthMM', 138, 'HeightMM', 71, ...
        'WidthPx', round(138*PX_PER_MM), 'HeightPx', round(71*PX_PER_MM), ...
        'AspectRatio', 138/71, 'DominantColor', [120, 45, 0]); % ירוק - Hue=120
    
    banknotes(end+1) = struct('Name', '100 NIS', 'Value', 100, 'Currency', 'ILS', ...
        'WidthMM', 138, 'HeightMM', 71, ...
        'WidthPx', round(138*PX_PER_MM), 'HeightPx', round(71*PX_PER_MM), ...
        'AspectRatio', 138/71, 'DominantColor', [25, 50, 0]); % חום-כתום - Hue=25
    
    banknotes(end+1) = struct('Name', '200 NIS', 'Value', 200, 'Currency', 'ILS', ...
        'WidthMM', 138, 'HeightMM', 71, ...
        'WidthPx', round(138*PX_PER_MM), 'HeightPx', round(71*PX_PER_MM), ...
        'AspectRatio', 138/71, 'DominantColor', [210, 45, 0]); % כחול - Hue=210
    
    % --- אירו (EUR) ---
    banknotes(end+1) = struct('Name', '10 Euro', 'Value', 10, 'Currency', 'EUR', ...
        'WidthMM', 127, 'HeightMM', 67, ...
        'WidthPx', round(127*PX_PER_MM), 'HeightPx', round(67*PX_PER_MM), ...
        'AspectRatio', 127/67, 'DominantColor', [5, 55, 0]); % אדום בהיר - Hue=5 (יותר מדויק)
    
    banknotes(end+1) = struct('Name', '20 Euro', 'Value', 20, 'Currency', 'EUR', ...
        'WidthMM', 133, 'HeightMM', 72, ...
        'WidthPx', round(133*PX_PER_MM), 'HeightPx', round(72*PX_PER_MM), ...
        'AspectRatio', 133/72, 'DominantColor', [220, 45, 0]); % כחול - Hue=220
    
    banknotes(end+1) = struct('Name', '50 Euro', 'Value', 50, 'Currency', 'EUR', ...
        'WidthMM', 140, 'HeightMM', 77, ...
        'WidthPx', round(140*PX_PER_MM), 'HeightPx', round(77*PX_PER_MM), ...
        'AspectRatio', 140/77, 'DominantColor', [30, 55, 0]); % כתום - Hue=30
end
